### ISSUE TITLE
get_geom_by_id(...) Assertion `table().has_geom_column()' failed

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/osm2pgsql#1177]
I'm trying to process a full history file extract via: `./osm2pgsql -d osm2 --append --slim  -P 5434  -O flex -S osmosis.lua mainz.osh.pbf -x`. Unfortunately, the process was aborted by an assertion failure:

`/osm2pgsql/src/flex-table.cpp:313: pg_result_t table_connection_t::get_geom_by_id(osmium::item_type, osmid_t) const: Assertion `table().has_geom_column()' failed.`

osmosis.lua refers to the example from #1174, which only contains tables without geometry.

Commit: a09e9f56028f3263f90533e4ad590d09a766a6f4

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff5d1d801 in __GI_abort () at abort.c:79
#2  0x00007ffff5d0d39a in __assert_fail_base (fmt=0x7ffff5e947d8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x55555598922f "table().has_geom_column()", file=file@entry=0x555555988b38 "/home/user/osm2pgsql/src/flex-table.cpp", 
    line=line@entry=313, 
    function=function@entry=0x55555598c880 <table_connection_t::get_geom_by_id(osmium::item_type, long) const::__PRETTY_FUNCTION__> "pg_result_t table_connection_t::get_geom_by_id(osmium::item_type, osmid_t) const") at assert.c:92
#3  0x00007ffff5d0d412 in __GI___assert_fail (assertion=0x55555598922f "table().has_geom_column()", file=0x555555988b38 "/home/user/osm2pgsql/src/flex-table.cpp", 
    line=313, 
    function=0x55555598c880 <table_connection_t::get_geom_by_id(osmium::item_type, long) const::__PRETTY_FUNCTION__> "pg_result_t table_connection_t::get_geom_by_id(osmium::item_type, osmid_t) const") at assert.c:101
#4  0x000055555590bb9f in table_connection_t::get_geom_by_id (this=0x555555cb4200, type=<unvollständiger Typ>, id=162755)
    at /home/user/osm2pgsql/src/flex-table.cpp:313
#5  0x000055555589185f in output_flex_t::delete_from_table (this=0x555555ca9560, table_connection=0x555555cb4200, type=<unvollständiger Typ>, osm_id=162755)
    at /home/user/osm2pgsql/src/output-flex.cpp:1123
#6  0x0000555555891993 in output_flex_t::delete_from_tables (this=0x555555ca9560, type=<unvollständiger Typ>, osm_id=162755)
    at /home/user/osm2pgsql/src/output-flex.cpp:1133
#7  0x00005555558919dd in output_flex_t::node_delete (this=0x555555ca9560, osm_id=162755) at /home/user/osm2pgsql/src/output-flex.cpp:1143
#8  0x0000555555891a6a in output_flex_t::node_modify (this=0x555555ca9560, node=...) at /home/user/osm2pgsql/src/output-flex.cpp:1158
#9  0x00005555558006f0 in osmdata_t::node_modify (this=0x7fffffffd4d0, node=...) at /home/user/osm2pgsql/src/osmdata.cpp:89
#10 0x000055555582ffc7 in parse_osmium_t::node (this=0x7fffffffd580, node=...) at /home/user/osm2pgsql/src/parse-osmium.cpp:167
#11 0x0000555555865179 in osmium::detail::apply_item_impl<parse_osmium_t&, osmium::memory::Item> (item=..., handler=...)
    at /home/user/osm2pgsql/contrib/libosmium/include/osmium/visitor.hpp:61
#12 0x0000555555862dd4 in osmium::apply_item<osmium::memory::Item, parse_osmium_t&> (item=...) at /home/user/osm2pgsql/contrib/libosmium/include/osmium/visitor.hpp:303
#13 0x000055555585f077 in osmium::apply_impl<osmium::io::InputIterator<osmium::io::Reader, osmium::memory::Item>, parse_osmium_t&> (it=..., end=...)
    at /home/user/osm2pgsql/contrib/libosmium/include/osmium/visitor.hpp:317
#14 0x000055555585a66e in osmium::apply<osmium::io::InputIterator<osmium::io::Reader, osmium::memory::Item>, parse_osmium_t&> (it=..., end=...)
---Type <return> to continue, or q <return> to quit---
   contrib/libosmium/include/osmium/visitor.hpp:324
#15 0x0000555555854c77 in osmium::apply<osmium::io::Reader, parse_osmium_t&> (c=...) at /home/user/osm2pgsql/contrib/libosmium/include/osmium/visitor.hpp:331
#16 0x000055555582fcde in parse_osmium_t::stream_file (this=0x7fffffffd580, filename="/home/user/btrfs/mainz.osh.pbf", fmt="auto") at /home/user/osm2pgsql/src/parse-osmium.cpp:133
#17 0x00005555557b4c3d in main (argc=13, argv=0x7fffffffdaa8) at /home/user/osm2pgsql/src/osm2pgsql.cpp:93
```

**Comment by lonvia** [comment]
Why on earth would you want process a history file with osm2pgsql? That never was and never will be supported. You must not have more than one version per object in a single run.

**Comment by lonvia** [comment]
I assume that was part of #1174, so closing here as well.

**Comment by mmd-osm** [comment]
I created this because the assertion failure doesn't give me any hint as to the unsupported file format really.

**Comment by joto** [comment]
This is part of the reason why I want #1167. Because then it will be easy to figure out that you are feeding a file to osm2pgsql that it will not be able to cope with and give you a nice error message. Until then we have to live with this garbage-in-garbage-out result.
