### ISSUE TITLE
regression-test.py assumes port 5432 ?

### ISSUE THREAD

**Issue by strk** [openstreetmap/osm2pgsql#211]
I got this failure running make check:

```
ERROR: runTest (__main__.BasicNonSlimTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/regression-test.py", line 413, in setUp
    self.setUpGeneric(self.parameters, full_import_file)
  File "tests/regression-test.py", line 376, in setUpGeneric
    self.assertEqual (proc.returncode, 0, "Execution of osm2pgsql with options: '%s' failed:\n%s\n%s\n" % (str(parameters), outp, outerr))
AssertionError: Execution of osm2pgsql with options: '[]' failed:

osm2pgsql SVN version 0.87.0 (64bit id space)

Using built-in tag processing pipeline
Osm2pgsql failed due to ERROR: Error: Connection to database failed: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
```

The socket PostgreSQL is running on is indeed /tmp/.s.PGSQL.5493 here. The PGPORT environment variable is set to 5493 and the PGHOST variable to /tmp. These variables are good for the 'psql' monitor to connect without specifying anything else.

Is the test not using env variables ?

**Comment by pnorman** [comment]
The build system has changed since this was filed, is it still an issue?

Make sure that you've got PGPORT set when you first run cmake.

**Comment by pnorman** [comment]
Closing as abandoned.
