### ISSUE TITLE
Failing Gazetteer regression tests

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/osm2pgsql#278]
With ed86d635cb
```
Running diff-import for basic case
********..........F
======================================================================
FAIL: runTest (__main__.BasicGazetteerTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/regression-test.py", line 480, in runTest
    self.executeStatements(self.initialStatements)
  File "tests/regression-test.py", line 365, in executeStatements
    " (" + sql_test_statements[i][2] + ") {" + str(self.parameters) +"}")
AssertionError: 14: Failed Gazetteer place count, expected 4102 but was 2837 (SELECT count(*) FROM place) {[]}

----------------------------------------------------------------------
Ran 40 tests in 100.642s

FAILED (failures=1)
*************************
```

e2fabbf2e2eeb passes, so the commit that broke it is somewhere in https://github.com/openstreetmap/osm2pgsql/compare/e2fabbf2e2eeb...ed86d635cb

**Comment by lonvia** [comment]
That's from 463ee491f25c9480d8708f0c9a78503d9a257bc6. Forgot to adapt the test there. The new results are correct. I'll fix the numbers tonight.
