### ISSUE TITLE
regression tests fail for optional Lua tag processing

### ISSUE THREAD

**Issue by mtmail** [openstreetmap/osm2pgsql#552]
I'm running `osm2pgsql/tests/regression-test.py` on Ubuntu 14.04 with `osm2pgsql SVN version 0.89.0-dev (64bit id space)` (latest version from github).

```
======================================================================
ERROR: runTest (__main__.MultipolygonSlimTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/Nominatim/osm2pgsql/tests/regression-test.py", line 452, in setUp
    self.setUpGeneric(self.parameters, multipoly_import_file)
  File "/home/vagrant/Nominatim/osm2pgsql/tests/regression-test.py", line 383, in setUpGeneric
    self.assertEqual (proc.returncode, 0, "Execution of osm2pgsql --slim with options: '%s' failed:\n%s\n%s\n" % (str(parameters), outp, outerr))
AssertionError: Execution of osm2pgsql --slim with options: '['--tag-transform-script', 'style.lua', '-k']' failed:

osm2pgsql SVN version 0.89.0-dev (64bit id space)

Using lua based tag processing pipeline with script style.lua
Error: Could not init lua tag transform, as lua support was not compiled into this version
Error: Failed to initialise tag processing.
Error occurred, cleaning up
```

According to the README lua support is optional. I argue those 8 tests should be skipped or issue warnings only if lua was not compiled.

**Comment by pnorman** [comment]
You're not running the latest version, but I think the same issue is still present with 0.91.0-dev
